config/routes.rb
Rails.application.routes.draw do
  resources :application_forms
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_form.rb
class ApplicationForm < ApplicationRecord
	  mount_uploader :upload_cv, CvUploader
	  has_many :qualitative_research_experiences
	 validates :name, presence: true
	 validates :cnic, presence: true
	 validates :age, presence: true
	 validates :gender, presence: true
	 validates :address, presence: true
	 validates :mobile_number, presence: true
	 validates :apply_for, presence: true
	 validates :highest_education, presence: true
	 validates :subject_or_areas, presence: true
	 validates :highest_education, presence: true
	 validates :subject_or_areas, presence: true
	 # validates :qualitative_research_experience, presence: true
	 validates :upload_cv, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/qualitative_research_experience.rb
class QualitativeResearchExperience < ApplicationRecord
  belongs_to :application_form
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/application_forms_controller.rb
class ApplicationFormsController < ApplicationController
  before_action :set_application_form, only: [:show, :edit, :update, :destroy]

  # GET /application_forms
  # GET /application_forms.json
  def index
    @application_forms = ApplicationForm.all
  end

  # GET /application_forms/1
  # GET /application_forms/1.json
  def show
  end

  # GET /application_forms/new
  def new
    @application_form = ApplicationForm.new
  end

  # GET /application_forms/1/edit
  def edit
    
  
  end

  # POST /application_forms
  # POST /application_forms.json
  def create
    @application_form = ApplicationForm.new(application_form_params)

    respond_to do |format|
      if @application_form.save
           qualitative_research_experiences = params[:application_form][:qualitative_research_experiences].reject { |c| c.empty? }
   qualitative_research_experiences.each do |n|
    QualitativeResearchExperience.create(application_form_id:@application_form.id,name:n)
   end
        format.html { redirect_to @application_form, notice: 'Application form was successfully created.' }
        format.json { render :show, status: :created, location: @application_form }
      else
        format.html { render :new }
        format.json { render json: @application_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /application_forms/1
  # PATCH/PUT /application_forms/1.json
  def update
    respond_to do |format|
      if @application_form.update(application_form_params)
        format.html { redirect_to @application_form, notice: 'Application form was successfully updated.' }
        format.json { render :show, status: :ok, location: @application_form }
      else
        format.html { render :edit }
        format.json { render json: @application_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /application_forms/1
  # DELETE /application_forms/1.json
  def destroy
    @application_form.destroy
    respond_to do |format|
      format.html { redirect_to application_forms_url, notice: 'Application form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application_form
      @application_form = ApplicationForm.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_form_params
      
      params.require(:application_form).permit(:name, :cnic, :age, :gender, :address, :mobile_number, :apply_for, :highest_education, :subject_or_areas, :upload_cv)
    end
end

app/helpers/application_forms_helper.rb
module ApplicationFormsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application_forms/_form.html.erb
<%= simple_form_for(@application_form) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :cnic %>
    <%= f.input :age , collection: 5..100%>
    <%= f.input :gender, collection: ['male','female']%>
    <%= f.input :address %>
    <%= f.input :mobile_number %>
    <%= f.input :apply_for %>
    <%= f.input :highest_education %>
    <%= f.input :subject_or_areas %>
    
    <%= f.input :qualitative_research_experiences, collection: ['Designed interview questions ','Conducted qualitative interviews','Analysed qualitative interviews','Reported qualitative research','Published qualitative research'],as: :check_boxes%>
    <%= f.input :upload_cv ,as: :file%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/application_forms/edit.html.erb
<h1>Editing Application Form</h1>

<%= render 'form', application_form: @application_form %>

<%= link_to 'Show', @application_form %> |
<%= link_to 'Back', application_forms_path %>

app/views/application_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Application Forms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cnic</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Address</th>
      <th>Mobile number</th>
      <th>Apply for</th>
      <th>Highest education</th>
      <th>Subject or areas</th>
      <th>Qualitative research experience</th>
      <th>Upload cv</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @application_forms.each do |application_form| %>
      <tr>
        <td><%= application_form.name %></td>
        <td><%= application_form.cnic %></td>
        <td><%= application_form.age %></td>
        <td><%= application_form.gender %></td>
        <td><%= application_form.address %></td>
        <td><%= application_form.mobile_number %></td>
        <td><%= application_form.apply_for %></td>
        <td><%= application_form.highest_education %></td>
        <td><%= application_form.subject_or_areas %></td>
        <td>
          <ul>
             <% application_form.qualitative_research_experiences.each do|listt| %>
             <li> <%=listt.name%></li>
         
          <%end%>
          </ul>
         
        </td>
        <td> <%= image_tag  (application_form.upload_cv.url), :size => "260x180" %></td>
        <td><%= link_to 'Show', application_form %></td>
        <td><%#= link_to 'Edit', edit_application_form_path(application_form) %></td>
        <td><%= link_to 'Destroy', application_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application Form', new_application_form_path %>

app/views/application_forms/new.html.erb
<h1>New Application Form</h1>

<%= render 'form', application_form: @application_form %>

<%= link_to 'Back', application_forms_path %>

app/views/application_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @application_form.name %>
</p>

<p>
  <strong>Cnic:</strong>
  <%= @application_form.cnic %>
</p>

<p>
  <strong>Age:</strong>
  <%= @application_form.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @application_form.gender %>
</p>

<p>
  <strong>Address:</strong>
  <%= @application_form.address %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @application_form.mobile_number %>
</p>

<p>
  <strong>Apply for:</strong>
  <%= @application_form.apply_for %>
</p>

<p>
  <strong>Highest education:</strong>
  <%= @application_form.highest_education %>
</p>

<p>
  <strong>Subject or areas:</strong>
  <%= @application_form.subject_or_areas %>
</p>

<p>
  <strong>Qualitative research experience:</strong>
  <ul>
      <% @application_form.qualitative_research_experiences.each do |list| %>
<li><%=list.name%></li>
  <%end%>
  </ul>

</p>

<p>
  <strong>Upload cv:</strong>

  <%= image_tag  (@application_form.upload_cv.url), :size => "260x180" %>
</p>

<%= link_to 'Edit', edit_application_form_path(@application_form) %> |
<%= link_to 'Back', application_forms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineAppForm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Page 1</a></li>
      <li><a href="#">Page 2</a></li>
      <li><a href="#">Page 3</a></li>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>